function varargout = PSL3R_signature(F, varargin)
[~, Fx, Fy, Fxx, Fxy, Fyy, Fxxx, Fxxy, Fxyy, Fyyy] = ...
    compute_derivatives(F, 3, varargin{:});

D = Fx.^2.*Fyy + Fy.^2.*Fxx - 2*Fx.*Fy.*Fxy;

% choice of frame depends on sign of D (which is itself an
% invariant)
i_dge0 = D >= 0;
b = zeros(size(Fx));
d = zeros(size(Fx));
d(i_dge0) = Fx(i_dge0) ./ sqrt(D(i_dge0));
b(i_dge0) = -Fy(i_dge0) ./ sqrt(D(i_dge0));
d(~i_dge0) = Fx(~i_dge0) ./ sqrt(-D(~i_dge0));
b(~i_dge0) = -Fy(~i_dge0) ./ sqrt(-D(~i_dge0));
%b = -d * Fy ./ Fx;

% what is this? which moving frame variable was set to zero -
% It was Fbar222
h = d./(6*D.*Fx) .* (-Fxxx.*Fy.^3 + 3*Fxxy.*Fy.^2.*Fx + ...
    -3*Fxyy.*Fx.^2.*Fy + Fyyy.*Fx.^3);

c = h.*Fx.^2./(d.*D) - (Fx.*Fxy - Fy.*Fxx) ./ D;

a = (1 - c.*Fy) ./ Fx;

% checked g
g = 1 ./ (2*Fx.^2) .* (Fxx + 2*c.*(Fx.*Fxy - Fy.*Fxx) + c.^2.*D);

% G is Fbar
Gx = a.*Fx + c.*Fy;
Gy = b.*Fx + d.*Fy;
Gxx = -2*a.*g.*Fx - 2*c.*g.*Fy + ...
    a.^2.*Fxx + 2*a.*c.*Fxy + c.^2.*Fyy;
Gxy = (-b.*g - a.*h).*Fx + (-d.*g - c.*h).*Fy + ...
    a.*b.*Fxx + (b.*c + a.*d).*Fxy + c.*d.*Fyy;
Gyy = -2*b.*h.*Fx - 2.*d.*h.*Fy + ...
    b.^2.*Fxx + 2*b.*d.*Fxy + d.^2.*Fyy;

Gxxx = 6*a.*g.^2.*Fx + ...
    6*c.*g.^2.*Fy + ...
    -6*a.^2.*g.*Fxx + ...
    -12*a.*c.*g.*Fxy + ...
    -6*c.^2.*g.*Fyy + ...
    a.^3.*Fxxx + ...
    3*a.^2.*c.*Fxxy + ...
    3*a.*c.^2.*Fxyy + ...
    c.^3.*Fyyy;

Gxxy = 2*g.*(b.*g + 2*a.*h).*Fx + ...
    2*g.*(d.*g + 2*c.*h).*Fy + ...
    -2*a.*(2*b.*g + a.*h).*Fxx + ...
    -4*(b.*c.*g + a.*d.*g + a.*c.*h).*Fxy + ...
    -2*c.*(2*d.*g + c.*h).*Fyy + ...
    a.^2.*b.*Fxxx + ...
    a.*(2*b.*c + a.*d).*Fxxy + ...
    c.*(b.*c + 2.*a.*d).*Fxyy + ...
    c.^2.*d.*Fyyy;

Gxyy = 2*h.*(2*b.*g + a.*h).*Fx + ...
    2*h.*(2*d.*g + c.*h).*Fy + ...
    -2*b.*(b.*g + 2*a.*h).*Fxx + ...
    -4*(b.*d.*g + b.*c.*h + a.*d.*h).*Fxy + ...
    -2*d.*(d.*g + 2*c.*h).*Fyy + ...
    a.*b.^2.*Fxxx + ...
    b.*(b.*c + 2*a.*d).*Fxxy + ...
    d.*(2*b.*c + a.*d).*Fxyy + ...
    d.^2.*c.*Fyyy;

Gyyy = 6*b.*h.^2.*Fx + ...
    6*d.*h.^2.*Fy + ...
    -6*b.^2.*h.*Fxx + ...
    -12*b.*d.*h.*Fxy + ...
    -6*d.^2.*h.*Fyy + ...
    b.^3.*Fxxx + ...
    3*b.^2.*d.*Fxxy + ...
    3*b.*d.^2.*Fxyy + ...
    d.^3.*Fyyy;

J1 = Gxxx.^2;
J2 = Gxxy.^4;
J3 = Gxyy.^6;

denom = sqrt(J1.^2 + J2.^2 + J3.^2);

I1 = acos(J3 ./ denom);
I2 = atan2(J2, J1);

varargout = {F.*J1./denom, F.*J2./denom, F.*J3./denom};

end